### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by santacl4ws** [dwservice/agent#12]
How do I uninstall DWService running on ubuntu?
I need to re install this as i removed it from the browser page and can not re-install it as it says there is no update.

**Comment by santacl4ws** [comment]
resolved by rm-rf /user/share/dwagent

**Comment by tlvu** [comment]
For others, in addition to `rm -rf /user/share/dwagent` have to do the following before:

```sh
systemctl stop dwagent
systemctl disable dwagent  # remove symlink /etc/systemd/system/multi-user.target.wants/dwagent.service
rm /etc/dwagent /etc/systemd/system/dwagent.service /etc/xdg/autostart/dwagent_systray.desktop
rm -rf /user/share/dwagent
```

These steps should really be in the FAQ https://www.dwservice.net/en/faq.html or added to the `dwagent.sh` script itself as an "Uninstall" option right below the "Install" option.

**Comment by skonsoft** [comment]
Hello,

Please can you add the uninstall script please ?

Using: Ubuntu 20.10

Regards,
