### ISSUE TITLE
Adjust dwagent installer

### ISSUE THREAD

**Issue by muonIT** [dwservice/agent#17]
Hello,
I think that the dwagent installer is too complicated for most of my users (!). I would like to adjust certain things (make runonfly the default, remove "close" button, adjust coloring/logo, make username and password more easily seeable).
I manage to get the agent.py running (as per Wiki), but how I would go about adjusting the ui/installer.py and have it compile to a pyc and integrated in the dwagent.exe I don't know.

Can you lend a hand there?

Cheers and thanks for the interesting software!
Udo Puetz

**Comment by dwservice** [comment]
> Can you lend a hand there?
Yes, I can compile it for you. I have VM and scripts to generate installer for all OS.

If you run agent\ui\test\test_installer.py you can simulate the GUI installer.

**Comment by muonIT** [comment]
OK, I've tried several things but I haven't been able to bring python (2.7 or 3) to get past the "import installer" thing. It seems that python and me are not compatible.. (I come from a C64 assembler and such background, but hey, python is soo easy...).

What I would like is that the dwagent.exe starts directly into the showing of "Username and Password". Also no text like "The session is active. To connect go to dwservice.net" 
(I'm translating from german here) but rather a big text "User: xxx-xxx-xxx-xx" and "Password: xxxx" and only a link to the installable program part in the lower right corner or such.
Like I wrote in the beginning: my users are extremely "simple": if the **can** misunderstand something - they **will** misunderstand it...

If you know what I mean I would be very happy to try it out. But I also try to get the test_installer.py running somehow...

Thanks again,
Udo Puetz

**Comment by muonIT** [comment]
I didn't manage to get the test_installer.py running - in neither python 2.7 nor 3.x. I've come past the "import installer" thing but then it has problems with print(..).

Anyway - I got an email from Danilo with instructions, in PDF format, how to adjust
- Images
- icons
- Text above and below User/PW number
- start the dwagent.exe into the display of User/PW right away

Yay - great! *Exactly* what I want.
Except: it doesn't work.
I've written to and fro with Danilo but all his instructions haven't worked.

I'm giving up on dwagent - would've been nice but I need support IF something isn't work. If that support is for money (e.g. 1800 number pay by the minute) - fine. But it has to work.
