### ISSUE TITLE
Fedora 31 Workstation - No active screen has been recognized. 

### ISSUE THREAD

**Issue by ztardik** [dwservice/agent#29]
I've installed the agent on Fedora 31 Workstation. Screen sharing was working when I set up the computer.
Then moved the computer to it's final location where we didn't had internet for approximately two weeks. After that the system updated itself and the screen sharing does not work anymore.
The message is always the same "No active screen has been recognized.". 
No error in logs.

**Comment by Lifeling** [comment]
I've seen this when running your desktop environment with Wayland as the display server. See if you can run your desktop session with xorg.

**Comment by ztardik** [comment]
> I've seen this when running your desktop environment with Wayland as the display server. See if you can run your desktop session with xorg.

That works!
`/etc/gdm/custom.conf >> WaylandEnable=false`
