### ISSUE TITLE
file transfer

### ISSUE THREAD

**Issue by marcelocecin** [dwservice/agent#3]
please consider including the file transfer feature

**Comment by mikhoul** [comment]
I'm not sure I understand ?

There is already a file transfert module:

![image](https://user-images.githubusercontent.com/5678673/54314787-f5b0a300-45b2-11e9-895d-f4ee9134815c.png)

![image](https://user-images.githubusercontent.com/5678673/54314893-34465d80-45b3-11e9-867a-04be48fc1f15.png)

**Comment by marcelocecin** [comment]
ok sorry about that

**Comment by mikhoul** [comment]
No problem I admit that the documentation could be improved a lot, I said to the author that I will improve it but I'm really busy right now but as soon as possible I will try to do a quick tutorial/manual to help with the basic functions of DWS..
