### ISSUE TITLE
Mac computer/keyboard can't input the @ character on login prompt of a remote Windows PC

### ISSUE THREAD

**Issue by yurj** [dwservice/agent#38]
Hi!

Our institution uses the email as username. Thus, to login, the user has to enter its email. When using the dwservice remote screen, a user with a Mac computer cannot input the @ character on his remote login prompt on a Windows machine. When he press it, nothing happen. @ works correctly after login, so it is a problem only on Windows login prompt.

This a resume of the problem:

User with mac -> remote connect to Windows PC via dwservice.net -> login prompt -> cannot input @ but can after login.

We are aware of "Send keyboard sequence" on upper screen, but it can't help (@ can't be done using the shift or ctrl or shift).

I can see a solution: can you add the @ char on the upper menù  "Send keyboard sequence" in dwservice.net site?

Is there anything else we can do?

**Comment by dwservice** [comment]
Hi in meantime I've add @ in "send keyboard sequence"

**Comment by yurj** [comment]
Hi!

 Thanks for the rapid support!

 I've tested it on remote Linux to Windows and @ prints the ò character on remote screen (screenshot below). I think this can be a keyboard mapping issue. I'll ask my colleague to test it in the Mac, to see if something has changed.

![at_o](https://user-images.githubusercontent.com/1100944/85561050-8afe6c00-b62b-11ea-8e53-1c898186a9b4.png)

**Comment by yurj** [comment]
I can confirm this happen also in a Mac (browser in Mac on dwservice.net -> remote computer with Windows).

**Comment by dwservice** [comment]
Please try again.

**Comment by yurj** [comment]
It works (sorry for the delay). You can close the issue.
