### ISSUE TITLE
Allow user to change agent id

### ISSUE THREAD

**Issue by bilaliz** [dwservice/agent#4]
Currently when a user is installing an agent they pick an ID that is later on added to the dashboard, however if they clone their disk there is no way they can use DWservice on the cloned device because there is no way to create a new agent id on a system where a previous agent already existed.

**Comment by ideamk** [comment]
Maybe reinstall dwagent in silent mode after cloning?
Documentation for silent mode: https://www.dwservice.net/en/faq.html
Section «Can I install the agent in silent mode?»

**Comment by bilaliz** [comment]
yeah tried that but it says agent already installed

**Comment by obzbdc** [comment]
I successfully made a new agent ID on a cloned ubuntu VM by doing the below:

1 - Clone existing VM with configured DWAgent installed.
2 - Shutdown original VM till done.
3 - Boot new VM
4 - kill dwagent process
5 - mv /usr/share/dwagent /usr/share/dwagent.old
6 - Rerun dwagent.sh and set up as normal
7 - Can now boot original VM without clashing

Good luck!
