### ISSUE TITLE
Keystrokes at Windows logon

### ISSUE THREAD

**Issue by garciamartinalex** [dwservice/agent#53]
Since today, any keystroke works when remote machine runs Windows and it's showing the welcome screen where you have to press Ctrl+Alt+Del to log in.
If I send that Ctrl+Alt+Del from LogMeIn (for example), I still can't write my username and password from DWService.
Only when I have done the whole log in process I can start using the keyboard from DWService on that remote machine.

**Comment by wiserafa2** [comment]
It's happening to me too! Same thing! But if I try multiple times opening the screen and sending CTRL + SHIFT + ESC then it start working, until I log in or log off from any user!

**Comment by dwservice** [comment]
There was a problem with an update. Now it work.
