### ISSUE TITLE
DWAgent for Linux server only using terminal without any X server

### ISSUE THREAD

**Issue by dtouzeau** [dwservice/agent#64]
Hi, 
I would like to know if dwservice can work on Linux servers that did not have any X server such as gnome or kde.

Just to have access to the unix console / terminal remotely

**Comment by JonnyTech** [comment]
Yes, I use it with raspbian lite which has no x-server - console, file transfer, etc works fine.

**Comment by dtouzeau** [comment]
Confirmed...  thanks !
